---------------------drop seq--------------------------------------
drop sequence Fact_Closed_Crimes_seq;
drop sequence Dim_Location_seq;
drop sequence Dim_Crime_Type_seq;
drop sequence Dim_Time_seq;
drop sequence Dim_Officer_seq;

--------------------------drop trig------------------------------
drop trigger Fact_Closed_Crimes_trig;
drop trigger Dim_Location_trig;
drop trigger Dim_Crime_Type_trig;
drop trigger Dim_Time_trig;
drop trigger Dim_Officer_trig;


-----------------drop tables---------------------------------------
DROP TABLE 	Fact_Closed_Crimes  CASCADE CONSTRAINTS;
DROP TABLE 	Dim_Location  CASCADE CONSTRAINTS;
DROP TABLE 	Dim_Crime_Type  CASCADE CONSTRAINTS;
DROP TABLE 	Dim_Time CASCADE CONSTRAINTS;
DROP TABLE 	Dim_Officer  CASCADE CONSTRAINTS;


---------------------------create SEQ------------------------
create sequence Fact_Closed_Crimes_seq start with 1 increment by 1;
create sequence Dim_Location_seq start with 1 increment by 1;
create sequence Dim_Crime_Type_seq start with 1 increment by 1;
create sequence Dim_Time_seq start with 1 increment by 1;
create sequence Dim_Officer_seq start with 1 increment by 1;
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'C:\Users\dahal\OneDrive\school work\OneDrive\Desktop\Initial Assignment Database(77466805)\SS_DDL_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "Fact_Closed_Crimes" entity.
CREATE TABLE Fact_Closed_Crimes(
	crime_key	INTEGER NOT NULL,
	time_id	INTEGER,
	location_id	INTEGER,
	crimetype_id	INTEGER,
	officer_id	INTEGER,
	no_of_crimes	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "Fact_Closed_Crimes".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Fact_Closed_Crimes PRIMARY KEY (crime_key)
);

-- Create a Database table to represent the "Dim_Time" entity.
CREATE TABLE Dim_Time(
	time_id	INTEGER NOT NULL,
	year	VARCHAR(8),
	month	VARCHAR(8),
	day	VARCHAR(8),
	-- Specify the PRIMARY KEY constraint for table "Dim_Time".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Dim_Time PRIMARY KEY (time_id)
);

-- Create a Database table to represent the "Dim_Crime_Type" entity.
CREATE TABLE Dim_Crime_Type(
	crimetype_id	INTEGER NOT NULL,
	crime_type_key	INTEGER,
	closure_status	VARCHAR(20),
	crime_type	VARCHAR(100),
	data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "Dim_Crime_Type".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Dim_Crime_Type PRIMARY KEY (crimetype_id)
);

-- Create a Database table to represent the "Dim_Location" entity.
CREATE TABLE Dim_Location(
	location_id	INTEGER NOT NULL,
	location_key	INTEGER,
	region_name	VARCHAR(20),
	street_name	VARCHAR(20),
	post_code	VARCHAR(20),
	city_name	VARCHAR(20),
	data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "Dim_Location".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Dim_Location PRIMARY KEY (location_id)
);

-- Create a Database table to represent the "Dim_Officer" entity.
CREATE TABLE Dim_Officer(
	officer_id	INTEGER NOT NULL,
	officer_key	INTEGER,
	full_name	VARCHAR(50),
	department	VARCHAR(20),
	rank	VARCHAR(20),
	data_source	VARCHAR(40),
	-- Specify the PRIMARY KEY constraint for table "Dim_Officer".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Dim_Officer PRIMARY KEY (officer_id)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "Fact_Closed_Crimes_Dim_Location" relationship

-- This constraint ensures that the foreign key of table "Fact_Closed_Crimes"
-- correctly references the primary key of table "Dim_Location"

ALTER TABLE Fact_Closed_Crimes ADD CONSTRAINT fk1_Fact_Closed_Crimes_to_Dim_Location FOREIGN KEY(location_id) REFERENCES Dim_Location(location_id);

-- Alter table to add new constraints required to implement the "Fact_Closed_Crimes_Dim_Officer" relationship

-- This constraint ensures that the foreign key of table "Fact_Closed_Crimes"
-- correctly references the primary key of table "Dim_Officer"

ALTER TABLE Fact_Closed_Crimes ADD CONSTRAINT fk2_Fact_Closed_Crimes_to_Dim_Officer FOREIGN KEY(officer_id) REFERENCES Dim_Officer(officer_id);

-- Alter table to add new constraints required to implement the "Fact_Closed_Crimes_Dim_Time" relationship

-- This constraint ensures that the foreign key of table "Fact_Closed_Crimes"
-- correctly references the primary key of table "Dim_Time"

ALTER TABLE Fact_Closed_Crimes ADD CONSTRAINT fk3_Fact_Closed_Crimes_to_Dim_Time FOREIGN KEY(time_id) REFERENCES Dim_Time(time_id);

-- Alter table to add new constraints required to implement the "Fact_Closed_Crimes_Dim_Crime_Type" relationship

-- This constraint ensures that the foreign key of table "Fact_Closed_Crimes"
-- correctly references the primary key of table "Dim_Crime_Type"

ALTER TABLE Fact_Closed_Crimes ADD CONSTRAINT fk4_Fact_Closed_Crimes_to_Dim_Crime_Type FOREIGN KEY(crimetype_id) REFERENCES Dim_Crime_Type(crimetype_id);


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
------------------- triggers for uniques id's---------------------
create or replace trigger Fact_Closed_Crimes_trig
before insert on Fact_Closed_Crimes
for each row
begin 
	if :NEW.crime_key is null then
		select Fact_Closed_Crimes_seq.nextval into :new.crime_key from SYS.DUAL;
	end if;
end;
/

create or replace trigger Dim_Crime_Type_trig
before insert on Dim_Crime_Type
for each row
begin
	if :new.crimetype_id is null then
		select Dim_Crime_Type_seq.nextval into :new.crimetype_id from SYS.DUAL;
	end if;
end;
/

create or replace trigger Dim_Time_trig
before insert on Dim_Time
for each row
begin
	if :new.time_id is null then
		select Dim_Time_seq.nextval into :new.time_id from SYS.DUAL;
	end if;
end;
/

create or replace trigger Dim_Location_trig
before insert on Dim_Location
for each row
begin
	if :new.location_id is null then
		select Dim_Location_seq.nextval into :new.location_id from SYS.DUAL;
	end if;
end;
/

create or replace trigger Dim_Officer_trig
before insert on Dim_Officer
for each row
begin
	if :new.officer_id is null then
		select Dim_Officer_seq.nextval into :new.officer_id from SYS.DUAL;
	end if;
end;
/